// Generated 2026-10-07 from workspace/medical-debt-tool/state-research/states.json
// DO NOT EDIT BY HAND. Edit the research file and re-run build_states.py.
window.MEDBILL_STATES = {
  "AK": {
    name: "Alaska",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Alaska has no state law setting hospital charity-care income cutoffs. Only the federal rule applies: nonprofit hospitals must publish a written financial-assistance policy with their own income cutoffs, and you have at least 240 days from the first bill to apply.",
    referral: {"name": "Alaska Division of Insurance, Consumer Services", "phone": "907-269-7900", "url": "https://www.commerce.alaska.gov/web/ins/Consumers"},
    sources: ["https://dollarfor.org/state_sheet/alaska/"],
  },
  "AL": {
    name: "Alabama",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Alabama has no state law setting income cutoffs for free or discounted hospital care. Nonprofit hospitals must have a written financial-assistance policy under the federal 501(r) rule, and must consider your application for at least 240 days after your first bill.",
    referral: {"name": "Legal Services Alabama", "phone": "1-866-456-4995", "url": "https://legalservicesalabama.org/2024/02/"},
    sources: ["https://dollarfor.org/state_sheet/alabama/"],
  },
  "AR": {
    name: "Arkansas",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Arkansas has no state charity-care law. Only the federal rule applies: nonprofit hospitals must have a written financial-assistance policy, and each hospital sets its own income cutoffs.",
    referral: {"name": "Arkansas Insurance Department, Consumer Services Division", "phone": "(800) 852-5494", "url": "https://arkansasag.gov/divisions/public-protection/finances/health-care/"},
    sources: ["https://dollarfor.org/state_sheet/arkansas/"],
  },
  "AZ": {
    name: "Arizona",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Arizona has no state charity-care law. Only the federal rule applies: nonprofit hospitals must have a written financial-assistance policy, and each hospital sets its own income cutoffs.",
    referral: {"name": "Arizona Department of Insurance and Financial Institutions, Consumer Protection Division", "phone": "(602) 364-2499", "url": "https://difi.az.gov/COMPLAINT"},
    sources: ["https://dollarfor.org/state_sheet/arizona/"],
  },
  "CA": {
    name: "California",
    kind: "special",
    freeFpl: null,
    discountFpl: null,
    notes: "California hospitals must maintain charity-care and discount-payment policies. Uninsured patients, or insured patients whose out-of-pocket costs exceeded 10% of income in the prior 12 months, with income at or below 400% of the poverty level must be allowed to apply \u2014 but the state sets no single free-care or discount cutoff; each hospital sets its own policy thresholds. California is one of six states requiring automatic (no-application) eligibility screening for some patients.",
    referral: {"name": "Health Consumer Alliance", "phone": "1-888-804-3536", "url": "https://healthconsumer.org"},
    sources: ["https://www.cdph.ca.gov/Programs/CHCQ/LCP/Pages/AFL-21-54.aspx", "http://hcai.ca.gov/wp-content/uploads/2020/10/AB-774_FairPricingPolicies.pdf", "https://hcai.ca.gov/document/hospital-bill-complaint-program-fact-sheet/", "https://kffhealthnews.org/health-care-costs/medical-debt-hospital-bills-presumptive-eligibility-explainer-charity-care/"],
  },
  "CO": {
    name: "Colorado",
    kind: "thresholds",
    freeFpl: null,
    discountFpl: 250,
    notes: "Under the 2021 Hospital Discounted Care law (HB 21-1198), hospitals must screen all uninsured patients \u2014 and any insured patient who asks for help \u2014 for public coverage and financial assistance. Patients at or below 250% of the federal poverty guidelines get discounted care, with bills capped at state-set rates, via a uniform application.",
    referral: {"name": "Colorado Consumer Health Initiative, Consumer Assistance Program", "phone": "303-839-1261", "url": "http://cohealthinitiative.org/"},
    sources: ["https://hcpf.colorado.gov/colorado-hospital-discounted-care", "https://www.Cpr.Org/2024/11/17/report-colorado-hospitals-patients-rights-access-to-discounts/"],
  },
  "CT": {
    name: "Connecticut",
    kind: "thresholds",
    freeFpl: 250,
    discountFpl: null,
    notes: "Since Oct 2024, state law requires hospitals to fully cover medically necessary care for patients enrolled in SNAP or WIC with verified household income at or below 250% of the poverty level, with no asset test and regardless of immigration status; TANF is added and enrollment counts as presumptive income proof from Jan 1, 2027. Most CT hospitals also offer sliding-scale help above 250%, but those cutoffs are set by each hospital, not state law.",
    referral: {"name": "Connecticut Office of the Healthcare Advocate", "phone": "866-466-4446", "url": "https://portal.ct.gov/oha/knowledge-base/categories/about-oha/contact-us"},
    sources: ["https://www.cga.ct.gov/2024/ba/pdf/2024HB-05320-R000149-BA.pdf", "https://www.cga.ct.gov/2024/TOB/H/PDF/2024HB-05320-R00-HB.PDF", "https://www.medicaldaily.com/connecticut-hospital-bills-financial-assistance-notice-law-479422"],
  },
  "DC": {
    name: "District of Columbia",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 500,
    notes: "The Medical Debt Mitigation Amendment Act of 2026 (substantive provisions in effect Oct 1, 2026) requires DC health facilities to give free medically necessary care at or below 200% of the poverty level and discounted care between 200% and 500%, with payment plans capped at 3% of monthly income. Hospitals must proactively screen patients; the law also bans reporting medical debt to credit bureaus and restricts collections.",
    referral: {"name": "DC Office of the Health Care Ombudsman", "phone": "1-877-685-6391", "url": "https://healthcareombudsman.dc.gov/page/about-health-care-ombudsman"},
    sources: ["https://www.creditandcollectionnews.com/d-c-enacts-broad-medical-debt-protections/", "https://www.mondaq.com/unitedstates/financial-services/1841620/dc-enacts-broad-medical-debt-protections", "https://www.jdsupra.com/legalnews/d-c-medical-debt-overhaul-becomes-law-3782950/", "https://infobytes.orrick.com/2026-09-04/washington-d-c-medical-debt-law-banning-credit-reporting-and-restricting-collections-takes-effect/"],
  },
  "DE": {
    name: "Delaware",
    kind: "thresholds",
    freeFpl: 300,
    discountFpl: 400,
    notes: "SB 13 (signed July 2026) sets uniform statewide standards: free care at or below 300% of the poverty level, at least 75% off between 300% and 350%, and at least 50% off between 350% and 400%, regardless of insurance status. It requires one statewide application, presumptive eligibility for Medicaid/SNAP enrollees, and hospital-based doctors must honor the hospital's assistance decision on their own bills.",
    referral: {"name": "Community Legal Aid Society (CLASI)", "phone": "302-575-0660", "url": "https://www.declasi.org/"},
    sources: ["https://legis.delaware.gov/json/BillDetail/GeneratePdfDocument?legislationId=143519&legislationTypeId=6&docTypeId=2&legislationName=SS1forSB13", "https://www.beckershospitalreview.com/finance/delaware-expands-charity-care-delays-hospital-price-caps-3-things-to-know/"],
  },
  "FL": {
    name: "Florida",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Florida law defines charity care (income at or below 200% of poverty) only for reporting and hospital-payment purposes; it does not require hospitals to provide free or discounted care. Each hospital sets its own policy, and nonprofit hospitals must have a written financial-assistance policy under the federal 501(r) rule.",
    referral: {"name": "Florida Legal Services", "phone": "850-385-7900", "url": "http://www.floridalegal.org/"},
    sources: ["https://FLSenate.gov/Laws/Statutes/2024/0154.304"],
  },
  "GA": {
    name: "Georgia",
    kind: "thresholds",
    freeFpl: 125,
    discountFpl: 200,
    notes: "Georgia's Indigent Care Trust Fund rules require participating hospitals to give free care to people below 125% of poverty, and free or reduced-price care on a sliding scale between 125% and 200%. You apply at the hospital; these rules apply to hospitals in the state's Trust Fund program.",
    referral: {"name": "Georgia Legal Services Program", "phone": "1-833-457-7529", "url": "https://www.glsp.org/who-we-are/"},
    sources: ["https://rules.sos.ga.gov/GAC/111-3-6", "https://kffhealthnews.org/health-care-costs/medical-debt-hospital-bills-presumptive-eligibility-explainer-charity-care/"],
  },
  "HI": {
    name: "Hawaii",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Hawaii has no state law setting hospital charity-care income cutoffs (the only state-mandated free care is at the Hawaii State Hospital for psychiatric services). Only the federal rule applies: nonprofit hospitals must publish a written financial-assistance policy with their own income cutoffs, and you have at least 240 days from the first bill to apply.",
    referral: {"name": "Hawaii Department of Commerce and Consumer Affairs, Insurance Division", "phone": "808-586-2790", "url": "https://cca.hawaii.gov/ins/"},
    sources: ["https://dollarfor.org/state_sheet/hawaii/"],
  },
  "IA": {
    name: "Iowa",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Iowa's charity-care law covers only public hospitals serving their own county's residents and sets no income cutoff. Federal 501(r) rules govern, so each hospital sets its own thresholds \u2014 ask the hospital for its financial-assistance policy and apply.",
    referral: {"name": "Iowa Legal Aid", "phone": "1-800-532-1275", "url": "https://iowalegalaid.org/"},
    sources: ["https://dollarfor.org/state_sheet/iowa/"],
  },
  "ID": {
    name: "Idaho",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Idaho has no state law setting hospital charity-care income cutoffs. Only the federal rule applies: nonprofit hospitals must publish a written financial-assistance policy with their own income cutoffs, and you have at least 240 days from the first bill to apply.",
    referral: {"name": "Idaho Department of Insurance, Consumer Affairs", "phone": "1-800-721-3272", "url": "https://doi.idaho.gov"},
    sources: ["https://dollarfor.org/state_sheet/idaho/", "https://triagecancer.org/state-laws/charity-care"],
  },
  "IL": {
    name: "Illinois",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 600,
    notes: "Illinois law covers uninsured patients only: non-rural hospitals must give free care at or below 200% of the poverty level and discounts up to 600%; rural and critical-access hospitals use lower cutoffs (free at 125%, discounts to 300%). You must apply within 90 days, and hospitals must screen some patients for aid before billing; a separate 2025 law bars hospitals from billing any patient below 138% of the poverty level.",
    referral: {"name": "Illinois Attorney General \u2014 Health Care Helpline", "phone": "1-877-305-5145", "url": "http://illinoisattorneygeneral.gov/"},
    sources: ["https://law.justia.com/codes/illinois/chapter-210/act-210-ilcs-89/", "https://legalclarity.org/illinois-charity-care-eligibility-application-and-compliance/", "https://kffhealthnews.org/health-care-costs/medical-debt-hospital-bills-presumptive-eligibility-explainer-charity-care/", "https://www.wcia.com/illinois-capitol-news/new-illinois-law-impacts-healthcare-begins-in-2025/amp/"],
  },
  "IN": {
    name: "Indiana",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Indiana has no state charity-care threshold law (per state reporting, Aug 2024). Each hospital sets its own income cutoffs under the federal 501(r) rule, so ask the hospital for its financial-assistance policy and apply.",
    referral: {"name": "Indiana Legal Services", "phone": "(844) 243-8570", "url": "https://www.indianalegalservices.org/"},
    sources: ["https://indianacapitalchronicle.com/2024/08/05/charitable-care-stagnant-even-as-nonprofit-hospitals-sue-hoosiers/", "https://secure.in.gov/gov/files/EO-25-22-HFS-Report.pdf"],
  },
  "KS": {
    name: "Kansas",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Kansas has no state charity-care income threshold; each hospital sets its own under the federal 501(r) rule. In 2026 lawmakers considered HB 2736, which would require hospitals to screen patients for financial help before billing, but it sets no income cutoff.",
    referral: {"name": "Kansas Legal Services", "phone": "(316) 267-3975", "url": "https://www.kansaslegalservices.org/"},
    sources: ["https://healthbillcentral.com/charity-care/kansas", "https://kslegislature.gov/b2025_26/measures/documents/supp_note_hb2736_01_0000.pdf"],
  },
  "KY": {
    name: "Kentucky",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Kentucky law addresses hospital charity care but sets no minimum income cutoff, so each hospital sets its own eligibility rules; nonprofit hospitals must have a written policy under the federal 501(r) rule. Separately, the state's Team Kentucky program is cancelling qualifying medical debts automatically with no application needed.",
    referral: {"name": "KY Attorney General, Office of Consumer Protection", "phone": "502-696-5389", "url": "http://kentucky.gov/government/Pages/AgencyProfile.aspx?Title=Office+of+Consumer+Protection"},
    sources: ["https://dollarfor.org/state_sheet/kentucky/", "https://unduemedicaldebt.org/press-release/gov-beshear-to-relieve-250-million-in-medical-debt-for-more-than-130000-kentuckians/"],
  },
  "LA": {
    name: "Louisiana",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Louisiana has a hospital financial-assistance law, but it sets no income threshold \u2014 each hospital sets its own cutoffs (free-care cutoffs at private nonprofits range from 100% to 250% FPL, per the Lown Institute). Federal 501(r) also applies to nonprofits.",
    referral: {"name": "Louisiana Department of Insurance, Consumer Hotline", "phone": "1-800-259-5300", "url": "https://www.ldi.la.gov/onlineservices/ConsumerComplaintForm?preview=true&site_id=756"},
    sources: ["https://dollarfor.org/state_sheet/louisiana/", "https://lownhospitalsindex.org/wp-content/uploads/2025/04/Louisiana_state-report.pdf"],
  },
  "MA": {
    name: "Massachusetts",
    kind: "thresholds",
    freeFpl: 150,
    discountFpl: 300,
    notes: "The state Health Safety Net pays hospitals for care to uninsured and underinsured Massachusetts residents: free care at or below 150% of the poverty level, and partial help with an income-based sliding-scale deductible between 150% and 300%. You must be a MA resident, but you do not have to be uninsured.",
    referral: {"name": "Health Care For All HelpLine", "phone": "800-272-4232", "url": "https://hcfama.org/hcfas-helpline/"},
    sources: ["https://malegislature.gov/Bills/192/SD3422.pdf", "https://www.capecodhealth.org/app/files/public/c6b6f858-73ef-445c-bfb0-86ff23f2f68d/financial-assistance-policy-english-may25.pdf"],
  },
  "MD": {
    name: "Maryland",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 300,
    notes: "Maryland law requires hospitals to give free medically necessary care at or below 200% of the federal poverty level, and reduced-cost care between 200% and 300%, whether or not the patient has insurance. Patients on programs like SNAP, WIC, or free school lunch are automatically treated as eligible for free care, and hospitals must try to screen for this using information they already have.",
    referral: {"name": "Health Education and Advocacy Unit (MD Attorney General)", "phone": "1-877-261-8807", "url": "https://oag.maryland.gov/News/Pages/Attorney-General-Brown-Announces-Health-Education-and-Advocacy-Unit-Saved-Nearly-$2.6-Million-for-Patients-in-FY-2025-.aspx"},
    sources: ["https://mgaleg.maryland.gov/2025RS/Statute_Google/ghg/19-214.1.pdf", "https://regulations.justia.com/states/maryland/title-10/part-5/subtitle-37/chapter-10-37-10/section-10-37-10-26/"],
  },
  "ME": {
    name: "Maine",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: null,
    notes: "A 2025 law (effective July 2026, 22 MRS 1716-A) requires all Maine hospitals to give free medically necessary care to state residents at or below 200% of the poverty level, up from 150%. Patients between 201% and 400% must be offered income-based payment plans capped at 4% of monthly income (a payment cap, not a bill discount); hospitals must proactively notify eligible patients, use a uniform application, and allow appeals.",
    referral: {"name": "Consumers for Affordable Health Care", "phone": "1-800-965-7476", "url": "https://www.mainecahc.org/"},
    sources: ["https://mainelegislature.org/statutes/22/title22sec1716-A.pdf", "https://observer-me.com/2025/07/21/news/maine-hospitals-concerned-about-charity-care-expansion-and-medicaid-cuts/", "https://dollarfor.org/state_sheet/maine/"],
  },
  "MI": {
    name: "Michigan",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Michigan sets no income threshold for hospital charity care. Each hospital sets its own cutoffs in its written financial-assistance policy under the federal 501(r) rule, so ask the hospital for its policy and apply.",
    referral: {"name": "Michigan Attorney General \u2014 Consumer Protection", "phone": "877-765-8388", "url": "https://www.michigan.gov/ag/consumer-protection"},
    sources: ["https://dollarfor.org/state_sheet/michigan/"],
  },
  "MN": {
    name: "Minnesota",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Minnesota law bars hospitals from making unreasonable demands on charity-care applications but sets no specific income cutoff (per KFF Health News, May 2026). Each hospital sets its own cutoffs under the federal 501(r) rule, so ask the hospital for its policy and apply.",
    referral: {"name": "Minnesota Attorney General \u2014 Consumer Assistance Hotline", "phone": "1-800-657-3787", "url": "https://www.ag.state.mn.us/"},
    sources: ["https://kffhealthnews.org/health-care-costs/medical-debt-uninsured-minnesota-hospitals-among-least-charitable/"],
  },
  "MO": {
    name: "Missouri",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Missouri has no state charity-care law. Each hospital sets its own income cutoffs in its written financial-assistance policy under the federal 501(r) rule, so ask the hospital for its policy and apply.",
    referral: {"name": "Missouri Attorney General \u2014 Consumer Protection Hotline", "phone": "1-800-392-8222", "url": "https://ago.mo.gov/"},
    sources: ["https://dollarfor.org/state_sheet/missouri/"],
  },
  "MS": {
    name: "Mississippi",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Mississippi sets no income threshold for charity care. State law only lets each public hospital's board set its own rules for indigent patients, and requires a 'reasonable amount' of indigent care as a vague condition of tax exemption and certificate-of-need approval. Nonprofit hospitals follow federal 501(r) with hospital-set cutoffs.",
    referral: {"name": "Mississippi Insurance Department, Consumer Services", "phone": "(800) 562-2957", "url": "https://www.mid.ms.gov/"},
    sources: ["https://dollarfor.org/state_sheet/mississippi/", "https://hilltopinstitute.org/wp-content/uploads/hcbp/hcbp_docs/HCBP_CBL_MS.pdf"],
  },
  "MT": {
    name: "Montana",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Montana sets no income cutoffs for charity care \u2014 the state requires hospitals to have a charity-care policy but specifies no FPL thresholds. Only the federal rule applies: nonprofit hospitals must publish a written financial-assistance policy with their own cutoffs, and you have at least 240 days from the first bill to apply.",
    referral: {"name": "Montana State Auditor, Commissioner of Securities and Insurance", "phone": "1-800-332-6148", "url": "https://csimt.gov"},
    sources: ["https://dollarfor.org/state_sheet/montana/", "https://kffhealthnews.org/health-industry/montana-nonprofit-hospital-community-benefit-standards-oversight/"],
  },
  "NC": {
    name: "North Carolina",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 300,
    notes: "This is a state health-department program requirement, not a statute: all 99 NC hospitals agreed to these terms to receive extra Medicaid funds. They must give free care at or below 200% of poverty and 50%-75% discounts up to 300%, for insured and uninsured patients alike, and must screen patients for help without requiring an application (automatic charity care for homeless, Medicaid, SNAP, and WIC patients).",
    referral: {"name": "Legal Aid of North Carolina", "phone": "1-866-219-5262", "url": "https://www.legalaidnc.org/get-help/apply-online"},
    sources: ["https://dhhs.nc.gov/medical-debt-toolkit/download?attachment", "http://www.northcarolinahealthnews.org/2024/08/13/nc-medical-debt-relief-plan-11-hospitalmust-dos-for-hospitals/"],
  },
  "ND": {
    name: "North Dakota",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "North Dakota has no state law setting hospital charity-care income cutoffs. Only the federal rule applies: nonprofit hospitals must publish a written financial-assistance policy with their own income cutoffs, and you have at least 240 days from the first bill to apply.",
    referral: {"name": "North Dakota Insurance Department, Consumer Assistance", "phone": "1-800-247-0560", "url": "https://www.insurance.nd.gov"},
    sources: ["https://dollarfor.org/state_sheet/north-dakota/"],
  },
  "NE": {
    name: "Nebraska",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Nebraska has no state charity-care law. Each hospital sets its own income cutoffs in its written financial-assistance policy under the federal 501(r) rule, so ask the hospital for its policy and apply.",
    referral: {"name": "Legal Aid of Nebraska", "phone": "1-877-250-2016", "url": "https://www.legalaidofnebraska.org/"},
    sources: ["https://dollarfor.org/state_sheet/nebraska/"],
  },
  "NH": {
    name: "New Hampshire",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "NH has no state law setting income cutoffs for hospital charity care; the state uncompensated-care statute only funds hospital DSH payments. Federal 501(r) applies: nonprofit hospitals must have a written financial-assistance policy with their own eligibility limits, so cutoffs vary by hospital.",
    referral: {"name": "New Hampshire Legal Assistance", "phone": "1-800-639-5290", "url": "https://www.nhla.org/contact-us"},
    sources: ["https://dollarfor.org/state_sheet/new-hampshire/", "https://law.justia.com/codes/new-hampshire/2017/title-xii/chapter-167/section-167-64/"],
  },
  "NJ": {
    name: "New Jersey",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 300,
    notes: "NJ law requires acute-care hospitals to give free care at or below 200% of the poverty level and reduced charges on a sliding scale (patient pays 20% to 80%) up to 300%. It applies to NJ residents, insured patients included, regardless of immigration status. You must apply (up to 365 days after the first bill), and assets must be under $7,500 ($15,000 for families).",
    referral: {"name": "New Jersey Citizen Action Consumer Health Helpline", "phone": "1-888-654-3893", "url": "https://www.njcitizenaction.org/free-health-care-enrollment-assistance"},
    sources: ["https://www.nj.gov/health/hcf/documents/charitycare/charity_care_section.pdf", "https://dollarfor.org/state_sheet/new-jersey/"],
  },
  "NM": {
    name: "New Mexico",
    kind: "special",
    freeFpl: null,
    discountFpl: null,
    notes: "New Mexico sets no income cutoff for hospital charity care \u2014 hospitals set their own policies. But the 2021 Patients' Debt Collection Protection Act requires hospitals to screen uninsured patients for public coverage and financial assistance before seeking payment, and bans all collection actions (lawsuits, garnishment) against patients below 200% of the poverty level.",
    referral: {"name": "New Mexico Center on Law and Poverty", "phone": "505-255-2840", "url": "http://nmpovertylaw.org/find-services-and-benefits/legal-help/"},
    sources: ["https://www.nmlegis.gov/Sessions/21 Regular/bills/senate/SB0071.HTML", "https://www.cabq.gov/office-of-consumer-protection/news/alert-patient-debt-collection-protection-act", "https://dollarfor.org/state_sheet/new-mexico/"],
  },
  "NV": {
    name: "Nevada",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Nevada law (NRS 439B.300-340) defines 'indigent' as uninsured, ineligible for other coverage, with income below fixed dollar amounts set in statute: $438/month for one person, which is about 33% of the current poverty level (counties may use more generous definitions). Hospitals with 100+ beds in multi-hospital counties (Clark and Washoe) must provide free care to indigent inpatients totaling at least 0.6% of net revenue per year \u2014 a hospital-level obligation, not an open-ended individual entitlement.",
    referral: {"name": "Nevada Office for Consumer Health Assistance", "phone": "1-888-333-1597", "url": "https://ADSD.nv.gov/Programs/CHA/ExtRev/External_Review/"},
    sources: ["https://www.leg.state.nv.us/nrS/NRS-439B.html", "https://dollarfor.org/state_sheet/nevada/", "https://d288exxlbtx24f.cloudfront.net/Nev_Rev_Stat_439B.300-439B.340.pdf"],
  },
  "NY": {
    name: "New York",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 400,
    notes: "New York's Hospital Financial Aid Law requires hospitals to waive all charges for patients at or below 200% of the federal poverty level, and to offer discounted care up to 400% \u2014 including insured patients who exhausted their benefits or spent over 10% of household income on medical costs in the last year. Hospitals must use a uniform application.",
    referral: {"name": "Community Health Advocates", "phone": "1-888-614-5400", "url": "https://communityhealthadvocates.org"},
    sources: ["https://ag.ny.gov/press-release/2026/attorney-general-james-releases-guidance-help-new-yorkers-access-hospital", "https://www.lohud.com/story/news/2026/08/24/hospital-bill-financial-assistance-free-discounted-care/91437417007/"],
  },
  "OH": {
    name: "Ohio",
    kind: "thresholds",
    freeFpl: 100,
    discountFpl: null,
    notes: "Ohio's Hospital Care Assurance Program (HCAP) requires hospitals to provide basic, medically necessary hospital care free to Ohio residents who are not on Medicaid and earn at or below 100% of the federal poverty level. You must apply through the hospital; discounts above that level depend on each hospital's own financial-assistance policy.",
    referral: {"name": "UHCAN Ohio", "phone": "(614) 456-0060 ext. 233", "url": "https://uhcanohio.org"},
    sources: ["https://dam.assets.ohio.gov/image/upload/medicaid.ohio.gov/About Us/PoliciesGuidelines/HHTL/HHTL-3352-22-06.pdf", "https://uhcanohio.org/wp-content/uploads/2022/08/QA-Help-Paying-Medical-Bills.pdf"],
  },
  "OK": {
    name: "Oklahoma",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Oklahoma has no state charity-care law. Only the federal rule applies: nonprofit hospitals must have a written financial-assistance policy, and each hospital sets its own income cutoffs.",
    referral: {"name": "Oklahoma Insurance Department, Consumer Assistance Division", "phone": "1-800-522-0071", "url": "https://www.oid.ok.gov/consumers/insurance-basics/health-insurance/"},
    sources: ["https://dollarfor.org/state_sheet/oklahoma/"],
  },
  "OR": {
    name: "Oregon",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 400,
    notes: "Applies to nonprofit hospitals (nearly all Oregon hospitals). Income at or below 200% of the poverty level gets the full bill written off; income between 200% and 400% gets a sliding-scale discount of at least 25%. Hospitals must automatically screen uninsured patients, Medicaid enrollees, and anyone billed over $1,500 for a single visit before billing them \u2014 no application needed.",
    referral: {"name": "Oregon Division of Financial Regulation, Consumer Hotline", "phone": "1-888-877-4894", "url": "https://dfr.oregon.gov"},
    sources: ["https://olis.oregonlegislature.gov/liz/2019R1/Downloads/MeasureDocument/HB3076/B-Engrossed", "https://www.oregonlegislature.gov/bills_laws/lawsstatutes/2026orLaw0109.pdf", "https://kffhealthnews.org/health-care-costs/medical-debt-hospital-bills-presumptive-eligibility-explainer-charity-care/"],
  },
  "PA": {
    name: "Pennsylvania",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "PA only requires hospitals to have a financial-assistance policy; state law sets no income cutoffs. The state publishes 200% of poverty as a recommended standard, not a mandate. Federal 501(r) applies, so eligibility varies hospital by hospital and patients should check the hospital's own policy.",
    referral: {"name": "Pennsylvania Health Law Project", "phone": "1-800-274-3258", "url": "https://www.phlp.org/en/contact"},
    sources: ["https://dollarfor.org/state_sheet/pennsylvania/", "https://www.pa.gov/content/dam/copapwp-pagov/en/dhs/documents/docs/publications/documents/forms-and-pubs-omap/c_268692.pdf", "https://www.explorejeffersonpa.com/healthy/2025/03/19/help-with-medical-bills-difficult-to-access-despite-hospital-charity-rules-study-finds-160687/"],
  },
  "RI": {
    name: "Rhode Island",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 300,
    notes: "RI sets a statewide minimum: free care at or below 200% of the poverty level and discounted care between 200% and 300% (each hospital sets its own sliding scale) for uninsured residents who do not qualify for government or employer coverage. Hospitals may add an asset test; you must apply and you can appeal a denial.",
    referral: {"name": "Rhode Island Legal Services", "phone": "800-662-5034", "url": "https://helprilaw.org"},
    sources: ["https://hilltop.institute/wp-content/uploads/hcbp/hcbp_docs/HCBP_CBL_RI.pdf", "https://dollarfor.org/state_sheet/rhode-island/", "https://www.chartercare.org/globalassets/olf-policy-for-charity-care_2024_01_22.pdf"],
  },
  "SC": {
    name: "South Carolina",
    kind: "thresholds",
    freeFpl: 100,
    discountFpl: 200,
    notes: "South Carolina's Medically Indigent Assistance Program (MIAP) requires general hospitals to provide unreimbursed care to eligible patients: full coverage of inpatient hospital services at or below 100% of poverty, and a sliding-scale copay between 100% and 200%. It is for people without insurance or other coverage; the hospital screens you and the state pays the hospital.",
    referral: {"name": "South Carolina Legal Services", "phone": "1-888-346-5592", "url": "https://sclegal.org/services/"},
    sources: ["https://www.law.cornell.edu/regulations/south-carolina/R-126-535", "http://www1.scdhhs.gov/internet/eligfm/FM%20227.pdf"],
  },
  "SD": {
    name: "South Dakota",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "South Dakota has no charity-care law for hospitals \u2014 state law only requires counties to help medically indigent residents with hospital expenses, with no FPL thresholds. Only the federal rule applies: nonprofit hospitals must publish a written financial-assistance policy with their own income cutoffs, and you have at least 240 days from the first bill to apply.",
    referral: {"name": "South Dakota Division of Insurance", "phone": "605-773-3563", "url": "https://dlr.sd.gov/insurance/"},
    sources: ["https://dollarfor.org/state_sheet/south-dakota/"],
  },
  "TN": {
    name: "Tennessee",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Tennessee sets no income cutoffs for free or discounted hospital care, and does not even require hospitals to have a financial-assistance policy \u2014 it only requires hospitals that have one to publish a short public summary. Nonprofit hospitals must have a written policy under the federal 501(r) rule.",
    referral: {"name": "Help4TN (statewide legal helpline)", "phone": "1-844-435-7486", "url": "https://www.tncourts.gov/programs/self-help-center/guide-to-free-or-reduced-rate-legal-services"},
    sources: ["https://hilltop.institute/wp-content/uploads/hcbp/hcbp_docs/HCBP_CBL_TN.pdf"],
  },
  "TX": {
    name: "Texas",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Texas requires nonprofit hospitals to have charity-care policies indexed to the poverty guidelines, but each hospital sets its own income cutoff \u2014 state law only requires the cutoff to fall between the county indigent-care level and 200% of the guidelines for reporting purposes, so there is no state-mandated free-care threshold. In practice, every Texas nonprofit hospital gives free care at or below 175% FPL (Texas Hospital Association).",
    referral: {"name": "Texas Department of Insurance, Consumer Help Line", "phone": "1-800-252-3439", "url": "http://www.tdi.texas.gov/consumer/get-help-with-an-insurance-complaint.html"},
    sources: ["https://www.tha.org/wp-content/uploads/2026/04/Charity-Care-FAQ-Feb-2026.pdf", "https://www.dshs.texas.gov/sites/default/files/chs/hosp/Forms/ASCBSPFP-2024.pdf"],
  },
  "UT": {
    name: "Utah",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Utah's charity-care law encourages volunteer free care through liability protections for providers, but it sets no income threshold. Only the federal rule applies: nonprofit hospitals must have a written financial-assistance policy with hospital-set cutoffs.",
    referral: {"name": "Utah Health Policy Project", "phone": "801-433-2299", "url": "http://www.healthpolicyproject.org/"},
    sources: ["https://dollarfor.org/state_sheet/utah/"],
  },
  "VA": {
    name: "Virginia",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Virginia law sets no income cutoffs for free or discounted hospital care, so each hospital writes its own policy. State law does require every hospital to screen every uninsured patient for Medicaid and its own financial-assistance program, and to post its charity-care policy where patients can see it; nonprofit hospitals also follow the federal 501(r) rule.",
    referral: {"name": "Virginia Legal Aid (statewide intake)", "phone": "1-866-534-5243", "url": "https://vsb.org/ML/Site/03_Legal-Aid/legal-aid.aspx"},
    sources: ["https://law.lis.virginia.gov/vacode/title32.1/chapter5/section32.1-137.010/", "http://law.lis.virginia.gov/vacode/32.1-137.01/"],
  },
  "VT": {
    name: "Vermont",
    kind: "thresholds",
    freeFpl: 250,
    discountFpl: 400,
    notes: "Act 119 (effective July 2024) sets statewide minimums for all VT hospitals: free care at or below 250% of the poverty level and at least a 40% discount between 251% and 400%. Hospitals may also apply a liquid-assets test, but cannot count your home, cars, or retirement savings.",
    referral: {"name": "Vermont Office of the Health Care Advocate", "phone": "1-800-917-7787", "url": "https://vtlawhelp.org/health"},
    sources: ["https://legislature.vermont.gov/Documents/2026/Workgroups/House%20Health%20Care/Bills/S.27/Witness%20Documents/S.27~Mike%20Fisher~Written%20Testimony~4-1-2025.pdf", "https://vtlawhelp.org/health-clinics-low-cost-health-care"],
  },
  "WA": {
    name: "Washington",
    kind: "thresholds",
    freeFpl: 200,
    discountFpl: 300,
    notes: "Every Washington hospital must give free care at or below 200% of the poverty level and discounts up to 300% \u2014 and these minimums cover both uninsured patients and insured patients' out-of-pocket costs. Larger hospitals (health systems with 3+ hospitals, or large hospitals in populous counties) must go further: free care to 300% and discounts to 400%.",
    referral: {"name": "Washington Office of the Insurance Commissioner, Consumer Advocacy", "phone": "1-800-562-6900", "url": "https://www.insurance.wa.gov"},
    sources: ["https://app.leg.wa.gov/Rcw/?cite=70.170&full=true&pdf=true", "https://lawfilesext.leg.wa.gov/law/RCWPDF/RCW%20%2070%20%20TITLE/RCW%20%2070.170%20%20CHAPTER/RCW%20%2070.170%20.060.pdf", "https://doh.wa.gov/sites/default/files/legacy/Documents/2300/HospPatientData/2018%20Charity%20Care%20in%20Washington%20Hospitals.pdf"],
  },
  "WI": {
    name: "Wisconsin",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Wisconsin has no state charity-care law. Each hospital sets its own income cutoffs in its written financial-assistance policy under the federal 501(r) rule, so ask the hospital for its policy and apply.",
    referral: {"name": "ABC for Health", "phone": "(608) 261-6939", "url": "http://www.safetyweb.org/"},
    sources: ["https://dollarfor.org/state_sheet/wisconsin/"],
  },
  "WV": {
    name: "West Virginia",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "West Virginia law sets no minimum income level for free or discounted hospital care; each hospital's board decides how much charity care it provides to qualify for property-tax exemption. Nonprofit hospitals must have a written financial-assistance policy under the federal 501(r) rule.",
    referral: {"name": "Legal Aid of West Virginia", "phone": "866-255-4370", "url": "https://legalaidwv.org/community-needs-assessment/"},
    sources: ["https://hilltopinstitute.org/wp-content/uploads/hcbp/hcbp_docs/HCBP_CBL_WV.pdf"],
  },
  "WY": {
    name: "Wyoming",
    kind: "fallback",
    freeFpl: null,
    discountFpl: null,
    notes: "Wyoming has no state law setting hospital charity-care income cutoffs. Only the federal rule applies: nonprofit hospitals must publish a written financial-assistance policy with their own income cutoffs, and you have at least 240 days from the first bill to apply.",
    referral: {"name": "Wyoming Department of Insurance", "phone": "1-800-438-5768", "url": "https://doi.wyo.gov"},
    sources: ["https://dollarfor.org/state_sheet/wyoming/"],
  },
};
